package com.rodrigo.TFG_server.Negocio;

public enum EventosNegocio {


    CREAR_EMPLEADO,
    EMPLEADO_CREADO,
    ERROR_CREAR_EMPLEADO,

    BUSCAR_EMPLEADO_BY_ID,
    BUSCAR_EMPLEADO_BY_EMAIL,
    ERROR_BUSCAR_EMPLEADO,

    ELIMINAR_EMPLEADO,
    ERROR_ELIMINAR_EMPLEADO,

    MODIFICAR_EMPLEADO,
    ERROR_MODIFICAR_EMPLEADO,

    EMAIL_YA_EXISTENTE,

    ERROR_LISTAR_EMPLEADOS,
    LISTAR_EMPLEADOS



}
