
package com.eduardosergio.TFG_server.negocio.helloWorld.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.0
 * Tue Feb 26 15:08:15 CET 2019
 * Generated source version: 3.2.0
 */

@XmlRootElement(name = "salute", namespace = "http://helloWorld.negocio.TFG_server.eduardosergio.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "salute", namespace = "http://helloWorld.negocio.TFG_server.eduardosergio.com/")

public class Salute {


}

