<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="HelloWorldService" 
targetNamespace="http://helloWorld.negocio.TFG_server.eduardosergio.com/" 
   xmlns:xsd="http://www.w3.org/2001/XMLSchema"
   xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
   xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
   xmlns:tns="http://helloWorld.negocio.TFG_server.eduardosergio.com/" 
   xmlns:wsp="http://www.w3.org/ns/ws-policy"
   xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
   xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
   xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702"   
   xmlns:t="http://docs.oasis-open.org/ws-sx/ws-trust/200512" 
   xmlns:wsaw="http://www.w3.org/2005/08/addressing" 
   xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex">
	<wsdl:types>
    	<schema xmlns="http://www.w3.org/2001/XMLSchema">
			<import namespace="http://helloWorld.negocio.TFG_server.eduardosergio.com/" schemaLocation="helloworld_schema1.xsd"/>
		</schema>
  	</wsdl:types>
  	<wsdl:message name="saluteResponse">
    	<wsdl:part name="parameters" element="tns:saluteResponse">
    	</wsdl:part>
  	</wsdl:message>
  	<wsdl:message name="salute">
    	<wsdl:part name="parameters" element="tns:salute">
    	</wsdl:part>
  	</wsdl:message>
  	<wsdl:portType name="HelloWorld">
    	<wsdl:operation name="salute">
      		<wsdl:input name="salute" message="tns:salute">
    		</wsdl:input>
      		<wsdl:output name="saluteResponse" message="tns:saluteResponse">
    		</wsdl:output>
    	</wsdl:operation>
  	</wsdl:portType>
  	<wsdl:binding name="HelloWorldServiceSoapBinding" type="tns:HelloWorld">
    	<wsp:PolicyReference URI="#HelloWorldBindingPolicy"/>
    	<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    	<wsdl:operation name="salute">
      		<soap:operation soapAction="urn:Salute" style="document"/>
      		<wsdl:input name="salute">
        		<soap:body use="literal"/>
        		<wsp:PolicyReference URI="#HelloWorldBinding_HelloWorld_Input_Policy"/>
      		</wsdl:input>
      		<wsdl:output name="saluteResponse">
        		<soap:body use="literal"/>
        		<wsp:PolicyReference URI="#HelloWorldBinding_HelloWorld_Output_Policy"/>
      		</wsdl:output>
    	</wsdl:operation>
  	</wsdl:binding>
  	<wsdl:service name="HelloWorldService">
    	<wsdl:port name="HelloWorldPort" binding="tns:HelloWorldServiceSoapBinding">
      		<soap:address location="http://localhost/TFG_server/services"/>
    	</wsdl:port>
  	</wsdl:service>
  	<wsp:Policy wsu:Id="HelloWorldBindingPolicy">
      <wsp:ExactlyOne>
         <wsp:All>
            <wsam:Addressing wsp:Optional="false">
               <wsp:Policy/>
            </wsam:Addressing>
            <sp:SymmetricBinding>
               <wsp:Policy>
                  <sp:ProtectionToken>
                     <wsp:Policy>
                        <sp:IssuedToken sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                           <sp:RequestSecurityTokenTemplate>
                              <t:TokenType>http://docs.oasis-open.org/wss/oasis-wss-saml-token-profile-1.1#SAMLV1.1</t:TokenType>
                              <t:KeyType>http://docs.oasis-open.org/ws-sx/ws-trust/200512/SymmetricKey</t:KeyType>
                              <t:KeySize>256</t:KeySize>
                           </sp:RequestSecurityTokenTemplate>
                           <wsp:Policy>
                              <sp:RequireInternalReference/>
                           </wsp:Policy>
                           <sp:Issuer>
                              <wsaw:Address>https://localhost:8443/TFG_STS/STS</wsaw:Address>
                              <wsaw:Metadata>
                                 <wsx:Metadata>
                                    <wsx:MetadataSection>
                                       <wsx:MetadataReference>
                                          <wsaw:Address>https://localhost:8443/TFG_STS/STS/mex</wsaw:Address>
                                       </wsx:MetadataReference>
                                    </wsx:MetadataSection>
                                 </wsx:Metadata>
                              </wsaw:Metadata>
                           </sp:Issuer>
                        </sp:IssuedToken>
                     </wsp:Policy>
                  </sp:ProtectionToken>
                  <sp:Layout>
                     <wsp:Policy>
                        <sp:Lax/>
                     </wsp:Policy>
                  </sp:Layout>
                  <sp:IncludeTimestamp/>
                  <sp:OnlySignEntireHeadersAndBody/>
                  <sp:AlgorithmSuite>
                     <wsp:Policy>
                        <sp:Basic256/>
                     </wsp:Policy>
                  </sp:AlgorithmSuite>
               </wsp:Policy>
            </sp:SymmetricBinding>
            <sp:Wss11>
               <wsp:Policy>
                  <sp:MustSupportRefIssuerSerial/>
                  <sp:MustSupportRefThumbprint/>
                  <sp:MustSupportRefEncryptedKey/>
               </wsp:Policy>
            </sp:Wss11>
            <sp:Trust13>
               <wsp:Policy>
                  <sp:MustSupportIssuedTokens/>
                  <sp:RequireClientEntropy/>
                  <sp:RequireServerEntropy/>
               </wsp:Policy>
            </sp:Trust13>
         </wsp:All>
      </wsp:ExactlyOne>
   </wsp:Policy>
   <wsp:Policy wsu:Id="HelloWorldBinding_HelloWorld_Input_Policy">
      <wsp:ExactlyOne>
         <wsp:All>
            <sp:EncryptedParts>
               <sp:Body/>
            </sp:EncryptedParts>
            <sp:SignedParts>
               <sp:Body/>
               <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing"/>
               <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing"/>
               <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing"/>
               <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing"/>
               <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing"/>
               <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing"/>
               <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing"/>
               <sp:Header Name="AckRequested" Namespace="http://docs.oasis-open.org/ws-rx/wsrm/200702"/>
               <sp:Header Name="SequenceAcknowledgement" Namespace="http://docs.oasis-open.org/ws-rx/wsrm/200702"/>
               <sp:Header Name="Sequence" Namespace="http://docs.oasis-open.org/ws-rx/wsrm/200702"/>
               <sp:Header Name="CreateSequence" Namespace="http://docs.oasis-open.org/ws-rx/wsrm/200702"/>
               <!--CXF uses by default for the docs/200702 ones: Namespace="http://schemas.xmlsoap.org/ws/2005/02/rm"/-->
            </sp:SignedParts>
         </wsp:All>
      </wsp:ExactlyOne>
   </wsp:Policy>
   <wsp:Policy wsu:Id="HelloWorldBinding_HelloWorld_Output_Policy">
      <wsp:ExactlyOne>
         <wsp:All>
            <sp:EncryptedParts>
               <sp:Body/>
            </sp:EncryptedParts>
            <sp:SignedParts>
               <sp:Body/>
               <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing"/>
               <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing"/>
               <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing"/>
               <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing"/>
               <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing"/>
               <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing"/>
               <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing"/>
               <sp:Header Name="AckRequested" Namespace="http://docs.oasis-open.org/ws-rx/wsrm/200702"/>
               <sp:Header Name="SequenceAcknowledgement" Namespace="http://docs.oasis-open.org/ws-rx/wsrm/200702"/>
               <sp:Header Name="Sequence" Namespace="http://docs.oasis-open.org/ws-rx/wsrm/200702"/>
               <sp:Header Name="CreateSequence" Namespace="http://docs.oasis-open.org/ws-rx/wsrm/200702"/>
            </sp:SignedParts>
         </wsp:All>
      </wsp:ExactlyOne>
   </wsp:Policy>
</wsdl:definitions>
